CREATE TABLE IF NOT EXISTS _presidential (
    id VARCHAR(28) NOT NULL PRIMARY KEY,
    election_id VARCHAR(28) NOT NULL DEFAULT '',
    president_id VARCHAR(28) NOT NULL DEFAULT '',
    vice_id VARCHAR(28) NOT NULL DEFAULT '',
    slogan VARCHAR(150) NOT NULL DEFAULT '',
    votes INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)